#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset
python3 manage.py makemigrations
python3 manage.py migrate --no-input
python3 manage.py collectstatic --no-input
gunicorn --bind 0.0.0.0:8000 backend.wsgi